export const GET_PRODUCT_URL = 'v1/products/'
export const GET_PRODUCTS_URL = 'v1/products/'
export const GET_PRODUCTS_BY_IDS_URL = 'v1/products/ids/'
export const CREATE_PRODUCTS_URL = 'v1/products/'
export const UPDATE_PRODUCTS_URL = 'v1/products/'
export const DELETE_PRODUCTS_URL = 'v1/products/'
export const GET_SIMILAR_IMAGE_PRODUCTS_URL = 'v1/images/'
