export const GET_USER_URL = 'v1/users/'
export const GET_USERS_URL = 'v1/users/'
export const CREATE_USER_URL = 'v1/users/'
export const UPDATE_USER_URL = 'v1/users/'
export const CHANGE_PASSWORD_URL = 'v1/users/'
export const DELETE_USER_URL = 'v1/users/'
